"""
Fault event generated by output guard or circuit breaker.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Optional


class FaultType(str, Enum):
    GARBLED_OUTPUT = "garbled_output"
    REPETITION = "repetition"
    INVISIBLE_CHARS = "invisible_chars"
    LONG_SILENCE = "long_silence"
    AGENT_LOOP = "agent_loop"
    TOOL_TIMEOUT = "tool_timeout"
    OVER_MAX_TOKENS = "over_max_tokens"
    UNKNOWN = "unknown"


@dataclass
class FaultEvent:
    fault_id: str = field(default_factory=lambda: f"fault_{uuid.uuid4().hex[:12]}")
    request_id: str = ""
    run_id: Optional[str] = None
    fault_type: FaultType = FaultType.UNKNOWN
    severity: int = 1
    message: str = ""
    detail: dict = field(default_factory=dict)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
